apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: amnesia-shh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/joaosouza129/amnesia-shh-frontend:sha-ae5df40
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_HOST
          value: "backend-service"
        - name: BACKEND_PORT
          value: "5050"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
