apiVersion: v1
kind: ConfigMap
metadata:
  name: amnesia-config
  namespace: amnesia-shh
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
  MAX_SECRET_BYTES: "10000"
  MAX_TTL_SECONDS: "604800"
  ALLOWED_ORIGIN: "https://amnesia-shh.duckdns.org"